# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b796c00d10289b68b9bd547e5d419a48ed9cc8cdef4fc757d5bc5ebec43163d2225f3781f8a2e3598963558f29e1404f63dc847f81937e63afe7fca81e8f0a8

test:
  secret_key_base: 1f874b81495afa8e46135d2e232a1fb92793ec6c30c400d48c3cb564f1a437f11b63fd9f58645697834c47241fd868939d93e89db0066c4b1dcaa085560e5ef5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
